---
abstract: 'Skeleton package that does nothing but reserve the namespace.'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment-Applications-SequencingSimulators-RNASeq-Polyester
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Bio::SeqAlignment::Applications::SequencingSimulators::RNASeq::Polyester:
    file: lib/Bio/SeqAlignment/Applications/SequencingSimulators/RNASeq/Polyester.pm
    version: '0.02'
requires:
  Bio::SeqAlignment::Components::Sundry::DocumentSequenceModifications: '0'
  Bio::SeqAlignment::Components::Sundry::IOHelpers: '0'
  Bio::SeqAlignment::Components::Sundry::Tailing: '0'
  Data::MessagePack: '0'
  File::Basename: '0'
  File::Spec: '0'
  FindBin: '0'
  Getopt::Long: '0'
  JSON: '0'
  YAML::Tiny: '0'
  constant: '0'
  perl: v5.36.0
  strict: '0'
  warnings: '0'
version: '0.02'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
